name: Manually Deploy to Heroku 2

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: bead2489-a14d-45dd-8c20-f9ab21e8ac93
          heroku_app_name: c2ptech-videohive_2
          heroku_email: videohive@c2ptech.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
